version: "{build}"

os: Windows Server 2012 R2

clone_folder: C:\gopath\src\github.com\gnosthi\quixical\

environment:
  GOPATH: c:\gopath
  QUIXICAL_BINARY: c:\gopath\src\github.com\gnoshti\quixical\quixical.exe

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
  - go build
  - ps: |
      go.exe test (go.exe list ./ | where { -not $_.Contains('/vendor/') })