# .goreleaser.yml
# Build Customization

builds:
  - binary: quixical
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive Customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - problems/*
